# Generated by Django 5.2.4 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('promoter', 'Promoter'), ('investor', 'Investor'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
