# Generated by Django 5.2.4 on 2025-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_last_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('promoter', 'Promoter'), ('admin', 'Admin'), ('deliveryman', 'Delivery Man'), ('warehouse', 'Warehouse Staff'), ('investor', 'Investor')], default='customer', max_length=20),
        ),
    ]
