# Generated by Django 5.2.4 on 2025-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('promoter', 'Promoter'), ('investor', 'Investor'), ('admin', 'Admin'), ('deliveryman', 'DeliveryMan')], default='customer', max_length=20),
        ),
    ]
