# Generated by Django 5.2.4 on 2025-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_user_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
