# Generated by Django 5.2.4 on 2025-10-04 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_custom_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Indian number. Examples: '+919876543210', '09876543210', '9876543210'.", regex='^(\\+91[\\-\\s]?|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be a valid 6-digit Indian pincode.', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
    ]
