# Generated by Django 5.2.4 on 2025-08-21 15:03

import promoter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='referral_code',
            field=models.CharField(default=promoter.models.generate_random_code, editable=False, max_length=50, unique=True),
        ),
    ]
