# Generated by Django 5.2.4 on 2025-07-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoter',
            old_name='desposit_amount',
            new_name='deposit_amount',
        ),
    ]
