# Generated by Django 5.2.4 on 2025-07-31 14:31

import promoter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0002_rename_desposit_amount_promoter_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='referral_code',
            field=models.CharField(default=promoter.models.generate_random_code, editable=False, unique=True),
        ),
    ]
