# Generated by Django 5.2.4 on 2025-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0003_promoter_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
