# Generated by Django 5.2.4 on 2025-08-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_promoter'),
        ('products', '0002_alter_category_slug_alter_product_category'),
        ('promoter', '0004_alter_promoter_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoter.promoter')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoter.promoter')),
            ],
        ),
    ]
