# Generated by Django 5.2.4 on 2025-08-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0005_promotercommission_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotercommission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
