# Generated by Django 5.2.4 on 2025-08-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0006_promotercommission_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotercommission',
            old_name='product',
            new_name='product_variant',
        ),
    ]
