[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_FRONTEND_URL = "https://beston.netlify.app"
  VITE_RAZORPAY_KEY = "rzp_test_fR3w70EKj1IvMf"
  VITE_RAZORPAY_KEY_ID = "rzp_test_fR3w70EKj1IvMf"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"