# Generated by Django 5.2.4 on 2025-09-27 04:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0003_deliverymanrequest_address_deliverymanrequest_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('out_for_delivery', 'Out for Delivery'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pickup_status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('rejected_pickup', 'Rejected at pickup'), ('damaged', 'Rejected - Damaged')], default='pending', max_length=20)),
                ('pickup_comment', models.TextField(blank=True, null=True)),
                ('warehouse_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('warehouse_comment', models.TextField(blank=True, null=True)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], default='razorpay', max_length=20)),
                ('user_upi', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('rejected_pickup', 'Rejected at pickup'), ('damaged', 'Rejected - Damaged')], default='pending', max_length=20)),
                ('pickup_comment', models.TextField(blank=True, null=True)),
                ('pickup_collected_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('warehouse_comment', models.TextField(blank=True, null=True)),
                ('warehouse_processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('admin_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^[6-9]\\d{9}$')])),
                ('address', models.TextField()),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit postal code', regex='^\\d{6}$')])),
                ('country', models.CharField(default='India', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('event', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('replacement_requested', 'Replacement Requested'), ('otp_delivery', 'OTP for Delivery'), ('otp_return', 'OTP for Return/Replacement Pickup')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='Rendered message, with placeholders replaced from payload')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dynamic data (order_id, OTP, tracking_id, etc.)')),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retries', models.PositiveIntegerField(default=0, help_text='Number of retry attempts for sending')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Optional future time for sending', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_applied', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Razorpay', 'Razorpay')], default='Cash on Delivery', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_restocked', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=50)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('refund_finalized', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_delivered', to='delivery.deliveryman')),
            ],
        ),
    ]
