# Generated by Django 5.2.4 on 2025-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_applied',
            field=models.BooleanField(default=False),
        ),
    ]
