# Generated by Django 5.2.4 on 2025-10-04 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, and hyphens.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
    ]
