# Generated by Django 5.2.4 on 2025-08-01 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_commission_order_commission_applied'),
        ('promoter', '0003_promoter_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promoter.promoter'),
        ),
    ]
