# Generated by Django 5.2.4 on 2025-10-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
