# Generated by Django 5.2.4 on 2025-08-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_deliverychargerule_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryChargeRule',
        ),
    ]
