# Generated by Django 5.2.4 on 2025-08-30 13:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0010_delete_deliverychargerule'),
        ('promoter', '0002_alter_promoter_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_upi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_delivered', to='delivery.deliveryman'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit postal code', regex='^\\d{6}$')]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_order_id'], name='orders_orde_razorpa_3caa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['razorpay_payment_id'], name='orders_orde_razorpa_ed0cb6_idx'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
