# Generated by Django 5.2.4 on 2025-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_returnrequest_alter_order_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_reason',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
