# Generated by Django 5.2.4 on 2025-08-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0013_alter_shippingaddress_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_returns', to='delivery.deliveryman'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='warehouse_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='warehouse_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
