# Generated by Django 5.2.4 on 2025-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_returnrequest_admin_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='pickup_verified',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('rejected', 'Rejected at pickup'), ('damaged', 'Rejected - Damaged')], default='pending', max_length=20),
        ),
    ]
