# Generated by Django 5.2.4 on 2025-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_returnrequest_pickup_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='admin_approved',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='warehouse_approved',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='admin_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='warehouse_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='pickup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('rejected_pickup', 'Rejected at pickup'), ('damaged', 'Rejected - Damaged')], default='pending', max_length=20),
        ),
    ]
