# Generated by Django 5.2.4 on 2025-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_returnrequest_admin_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='user_upi',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
