# Generated by Django 5.2.4 on 2025-09-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_returnrequest_user_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='user_upi',
            field=models.CharField(max_length=100),
        ),
    ]
