# Generated by Django 5.2.4 on 2025-09-01 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0018_alter_returnrequest_user_upi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='user_upi',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'refunded'), _negated=True), fields=('order_item',), name='unique_active_return_per_item'),
        ),
    ]
