# Generated by Django 5.2.4 on 2025-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_returnrequest_user_upi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=50),
        ),
    ]
