# Generated by Django 5.2.4 on 2025-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_refund_finalized_alter_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processed', 'Processed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=50),
        ),
    ]
