# Generated by Django 5.2.4 on 2025-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_assigned_at_alter_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('out_for_delivery', 'Out for Delivery'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
