# Generated by Django 5.2.4 on 2025-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_failed_at_orderitem_out_for_delivery_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
