# Generated by Django 5.2.4 on 2025-09-09 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverymanrequest_address_deliverymanrequest_phone_and_more'),
        ('orders', '0024_returnrequest_is_replacement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='returnrequest',
            name='unique_active_return_per_item',
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['refunded', 'replaced']), _negated=True), fields=('order_item',), name='unique_active_return_or_replacement_per_item'),
        ),
    ]
