# Generated by Django 5.2.4 on 2025-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_returnrequest_unique_active_return_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='is_replacement',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(choices=[('return', 'Return'), ('replacement', 'Replacement')], default='return', max_length=20),
            preserve_default=False,
        ),
    ]
