# Generated by Django 5.2.4 on 2025-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_returnrequest_is_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], max_length=20, null=True),
        ),
    ]
