# Generated by Django 5.2.4 on 2025-09-10 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverymanrequest_address_deliverymanrequest_phone_and_more'),
        ('orders', '0027_alter_returnrequest_refund_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pickup_status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('rejected_pickup', 'Rejected at pickup'), ('damaged', 'Rejected - Damaged')], default='pending', max_length=20)),
                ('pickup_comment', models.TextField(blank=True, null=True)),
                ('warehouse_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('warehouse_comment', models.TextField(blank=True, null=True)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='returnrequest',
            name='unique_active_return_or_replacement_per_item',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='replaced_at',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='replacement_status',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('manual', 'Manual')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'refunded'), _negated=True), fields=('order_item',), name='unique_active_return_per_item'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.order'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='pickup_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_replacements', to='delivery.deliveryman'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='replacementrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['delivered', 'failed', 'rejected']), _negated=True), fields=('order_item',), name='unique_active_replacement_per_item'),
        ),
    ]
