# Generated by Django 5.2.4 on 2025-09-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='new_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_origin', to='orders.order'),
        ),
    ]
