# Generated by Django 5.2.4 on 2025-09-11 11:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_replacementrequest_new_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='replacement_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
    ]
