# Generated by Django 5.2.4 on 2025-09-12 03:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_replacementrequest_price_difference_and_more'),
        ('products', '0015_rename_is_replacement_only_productvariant_allow_replacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='extra_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='replacement_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
