# Generated by Django 5.2.4 on 2025-09-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_replacementrequest_extra_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementrequest',
            name='extra_payment_amount',
        ),
        migrations.RemoveField(
            model_name='replacementrequest',
            name='price_difference',
        ),
        migrations.RemoveField(
            model_name='replacementrequest',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='replacementrequest',
            name='replacement_variant',
        ),
    ]
