# Generated by Django 5.2.4 on 2025-09-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_notification_otp_code_notification_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='otp_expires_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
