# Generated by Django 5.2.4 on 2025-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_notification_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('replacement_requested', 'Replacement Requested'), ('otp_delivery', 'OTP for Delivery'), ('otp_return', 'OTP for Return/Replacement Pickup')], max_length=50),
        ),
    ]
