services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo.wsgi:application"
    envVars:
      - fromDotEnv: true
    plan: free
databases:
  - name: ecommerce_db
    plan: free

envVars:
  - fromDotEnv: true
  - key: DATABASE_URL
    fromDatabase:
      name: ecommerce_db
      property: connectionString