# Generated by Django 5.2.4 on 2025-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='promoter_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
