# Generated by Django 5.2.4 on 2025-08-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_price_productvariant_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='additional_price',
        ),
    ]
