# Generated by Django 5.2.4 on 2025-08-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productvariant_additional_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the banner', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or tagline', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='Optional link when clicking banner', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order for carousel')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner in carousel?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
