# Generated by Django 5.2.4 on 2025-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_replacement_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='replacement_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='return_days',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
    ]
