# Generated by Django 5.2.4 on 2025-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_is_replacement_only_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_replacement_only',
            new_name='allow_replacement',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='is_returnable',
            new_name='allow_return',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='replacement_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='return_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
