# Generated by Django 5.2.4 on 2025-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_is_replacement_only_productvariant_allow_replacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this specific variant'),
        ),
    ]
