# Generated by Django 5.2.4 on 2025-09-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productvariant_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_avai_c23034_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_feature_55f52f_idx',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
