# Generated by Django 5.2.4 on 2025-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_banner_options_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order',), name='unique_active_order'),
        ),
    ]
