# Generated by Django 5.2.4 on 2025-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_banner_options_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(max_length=200),
        ),
    ]
