# Generated by Django 5.2.4 on 2025-10-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_name_alter_productvariant_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
