# Generated by Django 5.2.4 on 2025-07-28 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 28, 19, 48, 2, 279220)),
            preserve_default=False,
        ),
    ]
