# Generated by Django 5.2.4 on 2025-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouselog',
            name='action',
            field=models.CharField(choices=[('picked', 'Picked'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
