# Generated by Django 5.2.4 on 2025-08-06 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='investor.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='investors/')),
                ('address', models.TextField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investor.investor'),
        ),
        migrations.CreateModel(
            name='InvestorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='investor.investor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSaleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('profit_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('investor_share', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payout_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
                ('sale_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.productsaleshare')),
            ],
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investor'], name='investor_in_investo_16d209_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['confirmed'], name='investor_in_confirm_9f5073_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['product_variant'], name='investor_in_product_aac48a_idx'),
        ),
        migrations.AddIndex(
            model_name='productsaleshare',
            index=models.Index(fields=['investor'], name='investor_pr_investo_7f8237_idx'),
        ),
        migrations.AddIndex(
            model_name='productsaleshare',
            index=models.Index(fields=['period_start', 'period_end'], name='investor_pr_period__bb1f1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsaleshare',
            unique_together={('investor', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['investor'], name='investor_pa_investo_33541a_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='investor_pa_status_296a4b_idx'),
        ),
    ]
