# Generated by Django 5.2.4 on 2025-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentpayment',
            name='investment',
        ),
        migrations.AddField(
            model_name='investmentpayment',
            name='investments',
            field=models.ManyToManyField(related_name='payments', to='investor.investment'),
        ),
    ]
