# Generated by Django 5.2.4 on 2025-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_alter_investor_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='total_confirmed_investments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
