# Generated by Django 5.2.4 on 2025-08-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_investment_total_confirmed_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='total_confirmed_investments',
        ),
    ]
