# Generated by Django 5.2.4 on 2025-08-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_remove_investment_total_confirmed_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='net_worth',
        ),
        migrations.CreateModel(
            name='InvestmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='investor.investment')),
            ],
        ),
    ]
